import type { Theme } from 'theme-ui';

export const configDefault: Theme = {
  sizes: { 0: 0, 24: '1.5rem', 1200: '75rem' },
  space: {
    0: '0',
    2: '.125rem',
    4: '.25rem',
    8: '.5rem',
    12: '.75rem',
    16: '1rem',
    20: '1.25rem',
    24: '1.5rem',
    32: '2rem',
    48: '3rem',
    64: '4rem',
    80: '5rem',
    96: '6rem',
  },
  colors: {
    text: '#000',
    background: '#fff',
    primary: '#0d6efd',
    primaryLight: '#81b3fe',
    primaryDark: '#01337e',
    secondaryLight: '#bbc0c4',
    secondary: '#6c757d',
    secondaryDark: '#3b4044',
    white: '#fff',
    grey: '#ccc',
    black: '#000',
  },
  shadows: ['none', '0px 3px 10px 1px rgba(0, 0, 0, 0.21);'],
  fonts: {
    primary: 'Arial, sans-serif',
  },
  fontSizes: {
    12: '.75rem',
    14: '.875rem',
    16: '1rem',
    18: '1.125rem',
    20: '1.25rem',
    22: '1.25rem',
    24: '1.5rem',
    28: '1.75rem',
    32: '2rem',
    36: '2.25rem',
    40: '2.5rem',
    48: '3rem',
    56: '3.5rem',
    64: '4rem',
    72: '4.5rem',
  },
  fontWeights: {
    thin: 200,
    extraLight: 300,
    light: 400,
    regular: 'normal',
    medium: 600,
    semiBold: 700,
    bold: 800,
    black: 900,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  letterSpacings: {
    body: 'normalpx',
    caps: '0.2em',
  },
  buttons: {
    primary: {
      color: 'white',
      bg: 'primary',
      borderRadius: 0,
      px: 16,
      py: 8,
      '&:hover': {
        bg: 'text',
      },
    },
    primaryOutlined: {
      bg: 'white',
      color: 'primary',
      borderRadius: 0,
      border: 'solid 1px',
      borderColor: 'primary',
      cursor: 'pointer',
      px: 16,
      py: 8,
      '&:hover': {
        backgroundColor: 'primary',
        color: 'white',
      },
    },
    secondary: {
      color: 'white',
      bg: 'secondary',
      borderRadius: 0,
      px: 16,
      py: 8,
      '&:hover': {
        bg: 'white',
        color: 'secondary',
      },
    },
    secondaryOutlined: {
      bg: 'white',
      color: 'secondary',
      borderRadius: 0,
      border: 'solid 1px',
      borderColor: 'secondary',
      cursor: 'pointer',
      px: 16,
      py: 8,
      '&:hover': {
        backgroundColor: 'secondary',
        color: 'white',
      },
    },
    swiperDot: {
      borderRadius: '50%',
      bg: 'secondaryLight',
      height: '.5rem',
      width: '.5rem',
      p: 0,
      cursor: 'pointer',
      '&.active': {
        bg: 'secondary',
        height: '1rem',
        width: '1rem',
      },
    },
  },
  text: {
    title1: {
      fontFamily: 'primary',
      fontWeight: 'regular',
      fontSize: [32, 52],
      lineHeight: 'heading',
    },
    title2: {
      fontFamily: 'primary',
      fontWeight: 'light',
      fontSize: [40, 56],
      lineHeight: 'heading',
    },
    title3: {
      fontFamily: 'primary',
      fontWeight: 'light',
      fontSize: [36, 72],
      lineHeight: 'heading',
    },
    title4: {
      fontFamily: 'primary',
      fontWeight: 'light',
      fontSize: [36, 40],
      lineHeight: 'heading',
    },
    subtitle1: {
      fontFamily: 'primary',
      fontWeight: 'regular',
      fontSize: [20, 18],
      lineHeight: 'heading',
    },
    disclaimer1: {
      fontFamily: 'primary',
      fontWeight: 'light',
      fontSize: [12, 14],
      lineHeight: 'body',
      fontStyle: 'italic',
    },
    body1: {
      fontFamily: 'primary',
      fontWeight: 'light',
      fontSize: [12, 18],
      lineHeight: 'body',
    },
    body2: {
      fontFamily: 'primary',
      fontWeight: 'light',
      fontSize: [18, 20],
      lineHeight: 'body',
    },
    body3: {
      fontFamily: 'primary',
      fontWeight: 'regular',
      fontSize: 16,
      lineHeight: 'body',
    },
    body4: {
      fontFamily: 'primary',
      fontWeight: 'light',
      fontSize: 14,
      lineHeight: 'body',
    },
  },
};
